### ISSUE TITLE
Jonathan

### ISSUE THREAD

**Issue by jambdeep** [johnniewalker90/Equipo03#6]
- [x] Revisar la estructura de toda la carpeta y sugerir cambios para ser atendidos a la brevedad

**Comment by johnniewalker90** [comment]
ok la estructura funciona correctamente, dejo la liga para visualizar:
https://johnniewalker90.github.io/Equipo03/index.html

Les dejo cambios a continuación:

- [x] De acuerdo a la plantilla que mandé de productos realizar copia para producto 1 y 2 para René
- [x] De acuerdo a la plantilla que mandé de productos realizar copia para producto 3 y 4 para René
- [x] Ya enviados yo me encargaré de enlazarlos

**Comment by jambdeep** [comment]
Agradezco la precisión en tus cambios @johnniewalker90
