### ISSUE TITLE
Ivanna

### ISSUE THREAD

**Issue by jambdeep** [johnniewalker90/Equipo03#8]
- [x] Revisar el tamaño de las imágenes y decidir el tamaño mas conveniente para el proyecto

**Comment by ivannacer** [comment]
Todas las imágenes se les cambio la resolución ya que estaban arriba de 5000px y con nombres diferentes, ya que fueron bajados de depositorio. Se cambio el tamaño a 1300px por el lado más largo y se unificaron los nombres.

**Comment by jambdeep** [comment]
Muchas gracias por la aclaración @ivannacer
